import json
from typing import List, Dict
from ..models import ProcessedModel, ProcessedNews
from ..utils.date_utils import now_iso
from loguru import logger


def model_to_js_obj(m: ProcessedModel) -> str:
    """Convert a ProcessedModel to JavaScript object literal"""
    lines = ['    {']
    lines.append(f'      id: {js_str(m.id)},')
    lines.append(f'      name: {js_str(m.name)},')
    lines.append(f'      company: {js_str(m.company)},')
    lines.append(f'      logo: {js_str(m.logo)},')
    lines.append(f'      overallScore: {m.overallScore},')
    lines.append(f'      reasoning: {m.reasoning},')
    lines.append(f'      coding: {m.coding},')
    lines.append(f'      math: {m.math},')
    lines.append(f'      multimodal: {m.multimodal},')
    lines.append(f'      creativeWriting: {m.creativeWriting},')
    lines.append(f'      multilingual: {m.multilingual},')
    lines.append(f'      contextLength: {m.contextLength},')
    lines.append(f'      tags: {js_array(m.tags)},')
    lines.append(f'      description: {js_str(m.description)},')
    release = m.releaseDate or ''
    lines.append(f'      releaseDate: {js_str(release)},')
    # Optional new fields
    lines.append(f'      dataSource: {js_str(m.dataSource)},')
    if m.eloScore is not None:
        lines.append(f'      eloScore: {m.eloScore},')
    lines.append(f'      lastUpdated: {js_str(m.lastUpdated)},')
    lines.append('    }')
    return ',\n'.join(lines)


def news_to_js_obj(n: ProcessedNews) -> str:
    """Convert a ProcessedNews to JavaScript object literal"""
    lines = ['  {']
    lines.append(f'    id: {js_str(n.id)},')
    lines.append(f'    title: {js_str(n.title)},')
    lines.append(f'    summary: {js_str(n.summary)},')
    lines.append(f'    content: {js_str(n.content)},')
    lines.append(f'    source: {js_str(n.source)},')
    lines.append(f'    date: {js_str(n.date)},')
    lines.append(f'    category: {js_str(n.category)},')
    lines.append(f'    image: {js_str(n.image)},')
    lines.append(f'    url: {js_str(n.url)},')
    lines.append(f'    author: {js_str(n.author)},')
    lines.append(f'    lastUpdated: {js_str(n.lastUpdated)},')
    lines.append('  }')
    return ',\n'.join(lines)


def generate_leaderboard_js(classified: Dict[str, List[ProcessedModel]], output_path: str):
    """Generate src/data/leaderboard.js"""
    content = '// AI 大模型排行榜数据 (自动生成)\n'
    content += '// Generated by crawler at ' + now_iso() + '\n\n'
    
    for key, export_name in [('global', 'globalModels'), ('non_china', 'nonChinaModels'), ('china', 'chinaModels')]:
        models = classified.get(key, [])
        content += f'export const {export_name} = [\n'
        content += ',\n'.join(model_to_js_obj(m) for m in models)
        content += '\n];\n\n'
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    logger.info(f"Generated {output_path} ({sum(len(v) for v in classified.values())} models)")


def generate_news_js(news: List[ProcessedNews], output_path: str):
    """Generate src/data/news.js"""
    content = '// AI 大模型最新新闻数据 (自动生成)\n'
    content += '// Generated by crawler at ' + now_iso() + '\n\n'
    content += 'export const newsData = [\n'
    content += ',\n'.join(news_to_js_obj(n) for n in news)
    content += '\n];\n'
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    logger.info(f"Generated {output_path} ({len(news)} news items)")


def generate_version_js(model_count: int, news_count: int, data_sources: List[str], news_sources: List[str], output_path: str):
    """Generate src/data/version.js"""
    now = now_iso()
    content = f'''// 数据版本信息 (自动生成)
// Generated by crawler at {now}

export const dataVersion = {{
  lastUpdate: '{now}',
  leaderboardUpdate: '{now}',
  newsUpdate: '{now}',
  modelCount: {model_count},
  newsCount: {news_count},
  dataSources: {json.dumps(data_sources)},
  newsSources: {json.dumps(news_sources)},
  crawlInterval: '每小时',
  isAutoUpdate: true
}};
'''
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    logger.info(f"Generated {output_path}")


# Helper functions
def js_str(s: str) -> str:
    """Convert string to JS string literal"""
    if not s:
        return "''"
    escaped = s.replace('\\', '\\\\').replace("'", "\\'").replace('\n', '\\n').replace('\r', '')
    return f"'{escaped}'"


def js_array(arr: list) -> str:
    """Convert list to JS array literal"""
    if not arr:
        return '[]'
    items = ', '.join(js_str(item) for item in arr)
    return f'[{items}]'
