import json
import os
import tempfile
from typing import List, Dict, Any, Optional
from ..models import ProcessedModel, ProcessedNews
from ..utils.date_utils import now_iso
from loguru import logger


def _safe_js_value(val: Any) -> str:
    """Safely convert a Python value to a JS literal using json.dumps for strings."""
    if val is None:
        return 'null'
    if isinstance(val, bool):
        return 'true' if val else 'false'
    if isinstance(val, (int, float)):
        return str(val)
    return json.dumps(str(val), ensure_ascii=False)


def _safe_js_array(arr: List[str]) -> str:
    """Safely convert a list of strings to a JS array literal."""
    if not arr:
        return '[]'
    items = ', '.join(json.dumps(str(item), ensure_ascii=False) for item in arr)
    return f'[{items}]'


def _model_to_js_dict(m: ProcessedModel) -> str:
    """Convert a ProcessedModel to a JS object literal using safe serialization."""
    fields = [
        ('id', _safe_js_value(m.id)),
        ('name', _safe_js_value(m.name)),
        ('company', _safe_js_value(m.company)),
        ('logo', _safe_js_value(m.logo)),
        ('overallScore', str(m.overallScore)),
        ('reasoning', str(m.reasoning)),
        ('coding', str(m.coding)),
        ('math', str(m.math)),
        ('multimodal', str(m.multimodal)),
        ('creativeWriting', str(m.creativeWriting)),
        ('multilingual', str(m.multilingual)),
        ('contextLength', str(m.contextLength) if m.contextLength is not None else 'null'),
        ('tags', _safe_js_array(m.tags)),
        ('description', _safe_js_value(m.description)),
        ('releaseDate', _safe_js_value(m.releaseDate or '')),
        ('dataSource', _safe_js_value(m.dataSource)),
    ]
    if m.eloScore is not None:
        fields.append(('eloScore', str(m.eloScore)))
    fields.append(('lastUpdated', _safe_js_value(m.lastUpdated)))

    inner = ',\n      '.join(f'{k}: {v}' for k, v in fields)
    return f'    {{\n      {inner}\n    }}'


def _news_to_js_dict(n: ProcessedNews) -> str:
    """Convert a ProcessedNews to a JS object literal using safe serialization."""
    fields = [
        ('id', _safe_js_value(n.id)),
        ('title', _safe_js_value(n.title)),
        ('summary', _safe_js_value(n.summary)),
        ('content', _safe_js_value(n.content)),
        ('source', _safe_js_value(n.source)),
        ('date', _safe_js_value(n.date)),
        ('category', _safe_js_value(n.category)),
        ('image', _safe_js_value(n.image)),
        ('url', _safe_js_value(n.url)),
        ('author', _safe_js_value(n.author)),
        ('lastUpdated', _safe_js_value(n.lastUpdated)),
    ]
    inner = ',\n    '.join(f'{k}: {v}' for k, v in fields)
    return f'  {{\n    {inner}\n  }}'


def _atomic_write(path: str, content: str) -> None:
    """Write content to a file atomically to avoid partial writes on crash."""
    dir_name = os.path.dirname(path)
    fd, tmp_path = tempfile.mkstemp(dir=dir_name, suffix='.tmp')
    try:
        with os.fdopen(fd, 'w', encoding='utf-8') as f:
            f.write(content)
        os.replace(tmp_path, path)
    except Exception:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


def generate_leaderboard_js(classified: Dict[str, List[ProcessedModel]], output_path: str):
    """Generate src/data/leaderboard.js"""
    content = '// AI 大模型排行榜数据 (自动生成)\n'
    content += '// Generated by crawler at ' + now_iso() + '\n\n'

    for key, export_name in [('global', 'globalModels'), ('non_china', 'nonChinaModels'), ('china', 'chinaModels')]:
        models = classified.get(key, [])
        content += f'export const {export_name} = [\n'
        content += ',\n'.join(_model_to_js_dict(m) for m in models)
        content += '\n];\n\n'

    content += (
        'export const scoreCategories = [\n'
        "  { key: 'overallScore', label: '综合评分', color: '#00a3ff' },\n"
        "  { key: 'reasoning', label: '推理能力', color: '#00d9ff' },\n"
        "  { key: 'coding', label: '编程能力', color: '#10b981' },\n"
        "  { key: 'math', label: '数学能力', color: '#f59e0b' },\n"
        "  { key: 'multimodal', label: '多模态', color: '#8b5cf6' },\n"
        "  { key: 'creativeWriting', label: '创意写作', color: '#ec4899' },\n"
        "  { key: 'multilingual', label: '多语言', color: '#06b6d4' },\n"
        '];\n'
    )

    _atomic_write(output_path, content)
    logger.info(f"Generated {output_path} ({sum(len(v) for v in classified.values())} models)")


def generate_news_js(news: List[ProcessedNews], output_path: str):
    """Generate src/data/news.js with categories"""
    content = '// AI 大模型最新新闻数据 (自动生成)\n'
    content += '// Generated by crawler at ' + now_iso() + '\n\n'
    content += 'export const newsData = [\n'
    content += ',\n'.join(_news_to_js_dict(n) for n in news)
    content += '\n];\n\n'

    content += 'export const newsCategories = [\n'
    content += "  { key: 'all', label: '全部' },\n"
    content += "  { key: '产品发布', label: '产品发布' },\n"
    content += "  { key: '技术突破', label: '技术突破' },\n"
    content += "  { key: '开源发布', label: '开源发布' },\n"
    content += "  { key: '行业动态', label: '行业动态' },\n"
    content += "  { key: '行业应用', label: '行业应用' },\n"
    content += "  { key: '行业报告', label: '行业报告' },\n"
    content += '];\n'

    _atomic_write(output_path, content)
    logger.info(f"Generated {output_path} ({len(news)} news items)")


def generate_version_js(model_count: int, news_count: int, data_sources: List[str], news_sources: List[str], output_path: str):
    """Generate src/data/version.js"""
    now = now_iso()
    content = f'''// 数据版本信息 (自动生成)
// Generated by crawler at {now}

export const dataVersion = {{
  lastUpdate: '{now}',
  leaderboardUpdate: '{now}',
  newsUpdate: '{now}',
  modelCount: {model_count},
  newsCount: {news_count},
  dataSources: {json.dumps(data_sources)},
  newsSources: {json.dumps(news_sources)},
  crawlInterval: '每小时',
  isAutoUpdate: true
}};
'''
    _atomic_write(output_path, content)
    logger.info(f"Generated {output_path}")


def generate_model_details_js(models: List[ProcessedModel], output_path: str):
    """Generate src/data/modelDetails.js with curated and auto-generated details."""
    from ..manual_overrides import get_manual_detail

    content = '// AI 大模型详细信息 (自动生成)\n'
    content += '// Generated by crawler at ' + now_iso() + '\n\n'
    content += 'export const modelDetailsData = {\n'

    entries = []
    for m in models:
        detail = get_manual_detail(m.id)
        if detail:
            entries.append(_detail_to_js(m.id, detail))
        else:
            entries.append(_auto_detail_to_js(m))

    content += ',\n'.join(entries)
    content += '\n};\n\n'
    content += (
        'export const getModelDetail = (modelId) => {\n'
        '  return modelDetailsData[modelId] || {\n'
        "    fullDescription: '暂无详细信息',\n"
        '    capabilities: [],\n'
        '    useCases: [],\n'
        '    pricing: {}\n'
        '  };\n'
        '};\n'
    )

    _atomic_write(output_path, content)
    logger.info(f"Generated {output_path} ({len(entries)} models)")


# Auto-generated use case templates based on model tags
_USE_CASE_TEMPLATES = {
    '开源': ['开源社区项目', '本地部署', '学术研究'],
    '代码生成': ['代码开发', '软件工程', '自动化脚本'],
    '数学推理': ['数学研究', '竞赛训练', '数据建模'],
    '多模态': ['图像分析', '视频理解', '文档解析'],
    '创意写作': ['内容创作', '营销文案', '创意策划'],
    '多语言': ['多语言翻译', '国际化应用', '跨语言交流'],
    '中文优化': ['中文写作', '本地化应用', '中文客服'],
    '长文本分析': ['长文档处理', '论文分析', '合同审查'],
    '安全对齐': ['安全合规', '敏感内容过滤', '企业风控'],
    '企业应用': ['企业知识库', '智能客服', '业务流程自动化'],
    '推理强': ['复杂决策', '逻辑推理', '策略分析'],
    '性价比': ['高性价比应用', '大规模部署', '创业项目'],
    '实时数据': ['实时分析', '数据监控', '动态报告'],
    '教育': ['教育辅导', '在线学习', '知识问答'],
}


def _auto_detail_to_js(m: ProcessedModel) -> str:
    """Generate a basic auto-generated detail entry for a model without curated data."""
    # Derive capabilities from dimension scores
    dims = [
        ('推理能力', m.reasoning, '复杂逻辑推理与问题分析'),
        ('代码生成', m.coding, '多语言编程与代码调试'),
        ('数学能力', m.math, '数学问题求解与数学建模'),
        ('多模态', m.multimodal, '图像、视频等多模态内容理解'),
        ('创意写作', m.creativeWriting, '创意内容生成与文本创作'),
        ('多语言', m.multilingual, '多语言翻译与跨语言理解'),
    ]
    capabilities = [
        {'name': name, 'level': int(score), 'description': desc}
        for name, score, desc in dims
    ]

    # Derive use cases from tags
    use_cases = ['AI 助手', '内容生成']
    for tag in m.tags:
        if tag in _USE_CASE_TEMPLATES:
            for uc in _USE_CASE_TEMPLATES[tag]:
                if uc not in use_cases:
                    use_cases.append(uc)
    use_cases = use_cases[:8]

    # Build detail dict
    detail = {
        'fullDescription': (
            f'{m.name} 是 {m.company} 开发的大语言模型，'
            f'综合能力评分 {m.overallScore}/100。'
            + (f' 上下文窗口为 {m.contextLength:,} tokens。' if m.contextLength else '')
            + (f' 发布日期：{m.releaseDate}。' if m.releaseDate else '')
        ),
        'capabilities': capabilities,
        'useCases': use_cases,
        'pricing': {
            'input': '参见官方定价',
            'output': '参见官方定价',
            'context': f'{m.contextLength // 1000}K tokens' if m.contextLength else '未知',
        },
    }
    return _detail_to_js(m.id, detail)


def _detail_to_js(model_id: str, detail: dict) -> str:
    """Convert a model detail dict to JS object literal using safe serialization."""
    lines = [f"  {_safe_js_value(model_id)}: {{"]

    lines.append(f'    fullDescription: {_safe_js_value(detail.get("fullDescription", ""))},')

    caps = detail.get('capabilities', [])
    cap_lines = ['    capabilities: [']
    for i, cap in enumerate(caps):
        comma = ',' if i < len(caps) - 1 else ''
        cap_lines.append(
            f'      {{ name: {_safe_js_value(cap["name"])}, '
            f'level: {cap["level"]}, '
            f'description: {_safe_js_value(cap["description"])} }}{comma}'
        )
    cap_lines.append('    ],')
    lines.extend(cap_lines)

    cases = detail.get('useCases', [])
    lines.append(f'    useCases: {_safe_js_array(cases)},')

    pricing = detail.get('pricing', {})
    lines.append('    pricing: {')
    lines.append(f'      input: {_safe_js_value(pricing.get("input", ""))},')
    lines.append(f'      output: {_safe_js_value(pricing.get("output", ""))},')
    lines.append(f'      context: {_safe_js_value(pricing.get("context", ""))}')
    lines.append('    }')

    lines.append('  }')
    return '\n'.join(lines)
