import json
from typing import List, Dict
from ..models import ProcessedModel, ProcessedNews
from ..utils.date_utils import now_iso
from loguru import logger


def model_to_js_obj(m: ProcessedModel) -> str:
    """Convert a ProcessedModel to JavaScript object literal"""
    lines = ['    {']
    lines.append(f'      id: {js_str(m.id)},')
    lines.append(f'      name: {js_str(m.name)},')
    lines.append(f'      company: {js_str(m.company)},')
    lines.append(f'      logo: {js_str(m.logo)},')
    lines.append(f'      overallScore: {m.overallScore},')
    lines.append(f'      reasoning: {m.reasoning},')
    lines.append(f'      coding: {m.coding},')
    lines.append(f'      math: {m.math},')
    lines.append(f'      multimodal: {m.multimodal},')
    lines.append(f'      creativeWriting: {m.creativeWriting},')
    lines.append(f'      multilingual: {m.multilingual},')
    lines.append(f'      contextLength: {m.contextLength},')
    lines.append(f'      tags: {js_array(m.tags)},')
    lines.append(f'      description: {js_str(m.description)},')
    release = m.releaseDate or ''
    lines.append(f'      releaseDate: {js_str(release)},')
    # Optional new fields
    lines.append(f'      dataSource: {js_str(m.dataSource)},')
    if m.eloScore is not None:
        lines.append(f'      eloScore: {m.eloScore},')
    lines.append(f'      lastUpdated: {js_str(m.lastUpdated)},')
    lines.append('    }')
    return '\n'.join(lines)


def news_to_js_obj(n: ProcessedNews) -> str:
    """Convert a ProcessedNews to JavaScript object literal"""
    lines = ['  {']
    lines.append(f'    id: {js_str(n.id)},')
    lines.append(f'    title: {js_str(n.title)},')
    lines.append(f'    summary: {js_str(n.summary)},')
    lines.append(f'    content: {js_str(n.content)},')
    lines.append(f'    source: {js_str(n.source)},')
    lines.append(f'    date: {js_str(n.date)},')
    lines.append(f'    category: {js_str(n.category)},')
    lines.append(f'    image: {js_str(n.image)},')
    lines.append(f'    url: {js_str(n.url)},')
    lines.append(f'    author: {js_str(n.author)},')
    lines.append(f'    lastUpdated: {js_str(n.lastUpdated)},')
    lines.append('  }')
    return '\n'.join(lines)


def generate_leaderboard_js(classified: Dict[str, List[ProcessedModel]], output_path: str):
    """Generate src/data/leaderboard.js"""
    content = '// AI 大模型排行榜数据 (自动生成)\n'
    content += '// Generated by crawler at ' + now_iso() + '\n\n'
    
    for key, export_name in [('global', 'globalModels'), ('non_china', 'nonChinaModels'), ('china', 'chinaModels')]:
        models = classified.get(key, [])
        content += f'export const {export_name} = [\n'
        content += ',\n'.join(model_to_js_obj(m) for m in models)
        content += '\n];\n\n'
    
    # Add scoreCategories for frontend compatibility
    content += (
        'export const scoreCategories = [\n'
        "  { key: 'overallScore', label: '综合评分', color: '#00a3ff' },\n"
        "  { key: 'reasoning', label: '推理能力', color: '#00d9ff' },\n"
        "  { key: 'coding', label: '编程能力', color: '#10b981' },\n"
        "  { key: 'math', label: '数学能力', color: '#f59e0b' },\n"
        "  { key: 'multimodal', label: '多模态', color: '#8b5cf6' },\n"
        "  { key: 'creativeWriting', label: '创意写作', color: '#ec4899' },\n"
        "  { key: 'multilingual', label: '多语言', color: '#06b6d4' },\n"
        '];\n'
    )

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    logger.info(f"Generated {output_path} ({sum(len(v) for v in classified.values())} models)")


def generate_news_js(news: List[ProcessedNews], output_path: str):
    """Generate src/data/news.js with categories"""
    content = '// AI 大模型最新新闻数据 (自动生成)\n'
    content += '// Generated by crawler at ' + now_iso() + '\n\n'
    content += 'export const newsData = [\n'
    content += ',\n'.join(news_to_js_obj(n) for n in news)
    content += '\n];\n\n'
    
    # Add news categories
    content += 'export const newsCategories = [\n'
    content += "  { key: 'all', label: '全部' },\n"
    content += "  { key: '产品发布', label: '产品发布' },\n"
    content += "  { key: '技术突破', label: '技术突破' },\n"
    content += "  { key: '开源发布', label: '开源发布' },\n"
    content += "  { key: '行业动态', label: '行业动态' },\n"
    content += "  { key: '行业应用', label: '行业应用' },\n"
    content += "  { key: '行业报告', label: '行业报告' },\n"
    content += '];\n'
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    logger.info(f"Generated {output_path} ({len(news)} news items)")


def generate_version_js(model_count: int, news_count: int, data_sources: List[str], news_sources: List[str], output_path: str):
    """Generate src/data/version.js"""
    now = now_iso()
    content = f'''// 数据版本信息 (自动生成)
// Generated by crawler at {now}

export const dataVersion = {{
  lastUpdate: '{now}',
  leaderboardUpdate: '{now}',
  newsUpdate: '{now}',
  modelCount: {model_count},
  newsCount: {news_count},
  dataSources: {json.dumps(data_sources)},
  newsSources: {json.dumps(news_sources)},
  crawlInterval: '每小时',
  isAutoUpdate: true
}};
'''
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    logger.info(f"Generated {output_path}")


def generate_model_details_js(models: List[ProcessedModel], output_path: str):
    """Generate src/data/modelDetails.js with curated and auto-generated details."""
    from ..manual_overrides import get_manual_detail

    content = '// AI 大模型详细信息 (自动生成)\n'
    content += '// Generated by crawler at ' + now_iso() + '\n\n'
    content += 'export const modelDetailsData = {\n'

    entries = []
    for m in models:
        detail = get_manual_detail(m.id)
        if detail:
            entries.append(_detail_to_js(m.id, detail))
        else:
            entries.append(_auto_detail_to_js(m))

    content += ',\n'.join(entries)
    content += '\n};\n\n'
    content += (
        'export const getModelDetail = (modelId) => {\n'
        '  return modelDetailsData[modelId] || {\n'
        "    fullDescription: '暂无详细信息',\n"
        '    capabilities: [],\n'
        '    useCases: [],\n'
        '    pricing: {}\n'
        '  };\n'
        '};\n'
    )

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    logger.info(f"Generated {output_path} ({len(entries)} models)")


# Auto-generated use case templates based on model tags
_USE_CASE_TEMPLATES = {
    '开源': ['开源社区项目', '本地部署', '学术研究'],
    '代码生成': ['代码开发', '软件工程', '自动化脚本'],
    '数学推理': ['数学研究', '竞赛训练', '数据建模'],
    '多模态': ['图像分析', '视频理解', '文档解析'],
    '创意写作': ['内容创作', '营销文案', '创意策划'],
    '多语言': ['多语言翻译', '国际化应用', '跨语言交流'],
    '中文优化': ['中文写作', '本地化应用', '中文客服'],
    '长文本分析': ['长文档处理', '论文分析', '合同审查'],
    '安全对齐': ['安全合规', '敏感内容过滤', '企业风控'],
    '企业应用': ['企业知识库', '智能客服', '业务流程自动化'],
    '推理强': ['复杂决策', '逻辑推理', '策略分析'],
    '性价比': ['高性价比应用', '大规模部署', '创业项目'],
    '实时数据': ['实时分析', '数据监控', '动态报告'],
    '教育': ['教育辅导', '在线学习', '知识问答'],
}


def _auto_detail_to_js(m: ProcessedModel) -> str:
    """Generate a basic auto-generated detail entry for a model without curated data."""
    # Derive capabilities from dimension scores
    dims = [
        ('推理能力', m.reasoning, '复杂逻辑推理与问题分析'),
        ('代码生成', m.coding, '多语言编程与代码调试'),
        ('数学能力', m.math, '数学问题求解与数学建模'),
        ('多模态', m.multimodal, '图像、视频等多模态内容理解'),
        ('创意写作', m.creativeWriting, '创意内容生成与文本创作'),
        ('多语言', m.multilingual, '多语言翻译与跨语言理解'),
    ]
    capabilities = [
        {'name': name, 'level': int(score), 'description': desc}
        for name, score, desc in dims
    ]

    # Derive use cases from tags
    use_cases = ['AI 助手', '内容生成']
    for tag in m.tags:
        if tag in _USE_CASE_TEMPLATES:
            for uc in _USE_CASE_TEMPLATES[tag]:
                if uc not in use_cases:
                    use_cases.append(uc)
    use_cases = use_cases[:8]

    # Build detail dict
    detail = {
        'fullDescription': (
            f'{m.name} 是 {m.company} 开发的大语言模型，'
            f'综合能力评分 {m.overallScore}/100。'
            + (f' 上下文窗口为 {m.contextLength:,} tokens。' if m.contextLength else '')
            + (f' 发布日期：{m.releaseDate}。' if m.releaseDate else '')
        ),
        'capabilities': capabilities,
        'useCases': use_cases,
        'pricing': {
            'input': '参见官方定价',
            'output': '参见官方定价',
            'context': f'{m.contextLength // 1000}K tokens' if m.contextLength else '未知',
        },
    }
    return _detail_to_js(m.id, detail)


def _detail_to_js(model_id: str, detail: dict) -> str:
    """Convert a model detail dict to JS object literal."""
    lines = [f"  {js_str(model_id)}: {{"]

    # fullDescription
    lines.append(f'    fullDescription: {js_str(detail.get("fullDescription", ""))},')

    # capabilities
    caps = detail.get('capabilities', [])
    cap_lines = ['    capabilities: [']
    for i, cap in enumerate(caps):
        comma = ',' if i < len(caps) - 1 else ''
        cap_lines.append(
            f'      {{ name: {js_str(cap["name"])}, '
            f'level: {cap["level"]}, '
            f'description: {js_str(cap["description"])} }}{comma}'
        )
    cap_lines.append('    ],')
    lines.extend(cap_lines)

    # useCases
    cases = detail.get('useCases', [])
    lines.append(f'    useCases: {js_array(cases)},')

    # pricing
    pricing = detail.get('pricing', {})
    lines.append('    pricing: {')
    lines.append(f'      input: {js_str(pricing.get("input", ""))},')
    lines.append(f'      output: {js_str(pricing.get("output", ""))},')
    lines.append(f'      context: {js_str(pricing.get("context", ""))}')
    lines.append('    }')

    lines.append('  }')
    return '\n'.join(lines)
def js_str(s: str) -> str:
    """Convert string to JS string literal"""
    if not s:
        return "''"
    escaped = s.replace('\\', '\\\\').replace("'", "\\'").replace('\n', '\\n').replace('\r', '')
    return f"'{escaped}'"


def js_array(arr: list) -> str:
    """Convert list to JS array literal"""
    if not arr:
        return '[]'
    items = ', '.join(js_str(item) for item in arr)
    return f'[{items}]'
